[build]
  command = "npm ci install --force && npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "22.12.0", NODE_ENV = "production" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
